Make test failure messages more succinct
Given the following assertion:

    d = {1: 2, 3: 4}
    self.assertNotIn(1, d)

At least the nose and unittest2 test runners will print a message like
the following:

    AssertionError: 1 unexpectedly found in {1: 2, 3: 4}

Thus, the following assertion produces an unnecessarily verbose failure
message.

    d = {1: 2, 3: 4}
    self.assertNotIn(1, d, d)