Reset Pulp at start of RPM publish test case
`PublishTestCase` in module `pulp_smash.tests.rpm.api_v2.test_sync_publish` is
failing under Pulp 2.8 with an error like the following:

    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://192.168.121.19/pulp/repos/8367b7a5-5d04-4fe0-9a07-86e4354a101c/bear-4.1-1.noarch.rpm

A look through the system log on an affected system shows the following journal
entries:

    Feb 09 19:57:40 dev pulp[6882]: celery.worker.strategy:INFO: Received task: pulp.server.async.tasks._queue_reserved_task[d920bb95-ae9b-4970-97c2-3e3d6f2ef275]
    Feb 09 19:57:40 dev pulp[7006]: celery.worker.strategy:INFO: Received task: pulp.server.managers.content.upload.import_uploaded_unit[40392f83-78cd-4e2b-98e4-1befa42c9617]
    Feb 09 19:57:40 dev pulp[7006]: celery.worker.strategy:INFO: Received task: pulp.server.async.tasks._release_resource[e047d978-1211-4539-8678-42a874569af4]
    Feb 09 19:57:40 dev pulp[6882]: celery.worker.job:INFO: Task pulp.server.async.tasks._queue_reserved_task[d920bb95-ae9b-4970-97c2-3e3d6f2ef275] succeeded in 0.0702009970009s: None
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984) unexpected error occurred importing uploaded file
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984) Traceback (most recent call last):
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)   File "/home/vagrant/devel/pulp_rpm/plugins/pulp_rpm/plugins/importers/yum/upload.py", line 117, in upload
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)     handlers[type_id](repo, type_id, unit_key, metadata, file_path, conduit, config)
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)   File "/home/vagrant/devel/pulp_rpm/plugins/pulp_rpm/plugins/importers/yum/upload.py", line 382, in _handle_package
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)     unit.save_and_import_content(file_path)
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)   File "/home/vagrant/devel/pulp/server/pulp/server/db/model/__init__.py", line 797, in save_and_import_content
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)     self.save()
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)   File "/usr/lib/python2.7/site-packages/mongoengine/document.py", line 390, in save
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984)     raise NotUniqueError(message %% unicode(err))
    Feb 09 19:57:40 dev pulp[7173]: pulp_rpm.plugins.importers.yum.upload:ERROR: (7173-45984) NotUniqueError: Tried to save duplicate unique keys (E11000 duplicate key error index: pulp_database.units_rpm.$name_1_epoch_1_version_1_release_1_arch_1_checksumtype_1_checksum_1 dup key: { : "bear", : "0", : "4.1", : "1", : "noarch", : "sha256", : "7a831f9f90bf4d21027572cb503d20b702de8e8785b02c0397445c2e481d81b3" })
    Feb 09 19:57:40 dev pulp[7006]: celery.worker.job:INFO: Task pulp.server.managers.content.upload.import_uploaded_unit[40392f83-78cd-4e2b-98e4-1befa42c9617] succeeded in 0.104938584002s: {'details': {'errors': ['unexpected error occurred importing uploaded file']}, 'success_flag': False, 'summary': ''}

This traceback matches what is described in Pulp issue 1406. [1] Of interest is
that issue 1406 states that uploading the same content unit twice causes an HTTP
500 error, but an HTTP 404 error is currently received by the client.

This issue affects several test cases, and it is worked around by resetting Pulp
at the beginning of those test cases. Do the same here. Test suite results
before this commit:

    =========  ==========  ==================
    Pulp Ver.  Num. Tests  Test Suite Results
    =========  ==========  ==================
    2.7        10          OK
    dev (2.8)  0           FAILED (errors=1)
    =========  ==========  ==================

Test suite results after this commit:

    =========  ==========  ==================
    Pulp Ver.  Num. Tests  Test Suite Results
    =========  ==========  ==================
    2.7        10          OK
    dev (2.8)  10          OK
    =========  ==========  ==================