Ignore SSL verification warnings
Fix #4:

> Let's suppress SSL verification warnings. If a user sets "verify": False in
> their configuration file, then the responsibility for the fall-out of that
> decision lies with them. And if they do not suppress SSL verification, then a
> different warning is raised.

Do this by using `warnings.simplefilter`. Example results:

    $ python -m unittest2 discover pulp_smash.tests
    ....F...
    ======================================================================
    FAIL: test_body (pulp_smash.tests.test_login.LoginFailureTestCase)
    Assert that the response is valid JSON and does not have "key" and
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/ichimonji10/code/pulp-smash/pulp_smash/tests/test_login.py", line 70, in test_body
        self.assertEqual(set(self.response.json().keys()), ERROR_KEYS)
    AssertionError: Items in the first set but not the second:
    'auth_error_code'
    'http_request_method'
    Items in the second set but not the first:
    'href'

    ----------------------------------------------------------------------
    Ran 8 tests in 4.857s

    FAILED (failures=1)

The test failure is known about and should be present. See #9.