Update login test
Update method `pulp_smash.tests.test_login.LoginFailureTestCase.test_body`.
Formerly, the test asserted that the response body did not contain "key" and
"certificate" keys, as documented
[here](https://pulp.readthedocs.org/en/latest/dev-guide/integration/rest-api/authentication.html).
Now, the test asserts that the response body has the keys documented
[here](https://pulp.readthedocs.org/en/latest/dev-guide/conventions/exceptions.html#exception-handling),
plus the "href" key as documented
[here](https://github.com/PulpQE/pulp-smash/pull/9#issuecomment-147443359).

Test results:

    $ python -m unittest2 pulp_smash.tests.test_login
    F...
    ======================================================================
    FAIL: test_body (pulp_smash.tests.test_login.LoginFailureTestCase)
    Assert that the response is valid JSON and does not have "key" and
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "pulp_smash/tests/test_login.py", line 70, in test_body
        self.assertEqual(set(self.response.json().keys()), ERROR_KEYS)
    AssertionError: Items in the first set but not the second:
    u'http_request_method'
    u'auth_error_code'
    Items in the second set but not the first:
    u'href'

    ----------------------------------------------------------------------
    Ran 4 tests in 1.319s

    FAILED (failures=1)